config/routes.rb
Rails.application.routes.draw do
  root 'metrics#index'

  get 'metric_values/index'
  get 'metric_values/edit'
  post 'metric_values/update'
  get 'metrics/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :access_token

  def client_credentials_flow
    conn = Faraday.new
    response = conn.post 'https://api.hoopla.net/oauth2/token',
                         grant_type: 'client_credentials',
                         response_type: 'token',
                         client_id: 'aad6311c-d5bf-4048-b4a8-c187a231d037',
                         client_secret: 'abacf08f528a5931d490f3dffb708fca95c2d72f3a4f'

    JSON.parse(response.body)
  end

  def access_token
    if @auth_response.nil?
      @auth_response = client_credentials_flow
    end
    @auth_response['access_token']
  end

end

app/controllers/metric_values_controller.rb
class MetricValuesController < ApplicationController
  def index
    href = params.require('href')
    owner = params.require('owner')
    @metric_values = get_metric_values(access_token, href, owner)
    @metric_values
  end

  def edit
    href = params.require('href')
    @metric_value = get_metric_values(access_token, href)
  end

  def update
    @metric = JSON.parse(params.require('metric'))
    value = params.require('value')
    update_metric_value(access_token, @metric, value)
    redirect_to metric_values_index_url(href: @metric['href'], owner: @metric['metric']['href'])
  rescue StandardError => e
      flash[:error] = "Error: #{e.message}"
  end

  private

  def get_metric_values(access_token, href, owner = nil)
    conn = Faraday.new
    resp = conn.get do |req|
      req.url "#{href}" #"#{href}?owner.href=#{owner}"
      req.headers['Authorization'] = "Bearer " + access_token
    end
    JSON.parse(resp.body)
  end

  def update_metric_value(access_token, metric, value)
    payload = [{
        href: metric['href'],
        metric: {
            href: metric['metric']['href']
        },
        owner: {
            kind: metric['owner']['kind'],
            href: metric['owner']['href']
        },
        value: value
    }]

    conn = Faraday.new
    resp = conn.put do |req|
      req.url metric['href']
      req.headers['Authorization'] = "Bearer " + access_token
      req.headers['Content-Type'] = 'application/vnd.hoopla.metric-value+json'
      req.body = payload
    end
    JSON.parse(resp.body)
  end
end

app/controllers/metrics_controller.rb
class MetricsController < ApplicationController
  def index
    @metrics = get_metrics(access_token)
  end

  def get_metrics(access_token)
    conn = Faraday.new
    resp = conn.get do |req|
      req.url 'https://api.hoopla.net/metrics'
      req.headers['Authorization'] = "Bearer " + access_token
    end
    JSON.parse(resp.body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/metric_values_helper.rb
module MetricValuesHelper
end

app/helpers/metrics_helper.rb
module MetricsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoopla</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/metric_values/_metric_values.html.erb
<tr>
    <td><%= link_to metric_value['value'], metric_values_edit_path(href: metric_value['href']) %></td>
    <td><%= metric_value['name'] %></td>
    <td><%= metric_value['user'] %></td>
</tr>

app/views/metric_values/edit.html.erb
<h1>MetricValue Edit</h1>
<%= form_tag("/metric_values/update", method: "post") do %>
    <%= hidden_field_tag(:metric, @metric_value.to_json) %>
    <%= label_tag(:value, "Metric Value") %>
    <%= text_field_tag(:value, @metric_value['value']) %>
    <%= submit_tag("Save") %>
<% end %>

app/views/metric_values/index.html.erb
<h1>Metric Values</h1>
<%= link_to 'Back to Metrics', metrics_index_path %>
<table>
    <tr>
        <th>Name</th>
        <th>Value</th>
        <th>User</th>
    </tr>
    <%= render partial: 'metric_values', collection: @metric_values, as: :metric_value %>
</table>

app/views/metric_values/update.html.erb
<h1>MetricValue Update</h1>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= link_to 'Back to Metric Values', metric_values_index_url(href: @metric['href'][0, @metric['href'].rindex('/')], owner: @metric['metric']['href']) %>

app/views/metrics/_metrics.html.erb
<tr>
    <td><%= link_to metric['name'],
                    metric_values_index_path(href: metric['links'][0]['href'],
                                             owner: metric['href'])
    %></td>
    <td><%= metric['type'] %></td>
    <td><%= metric['format_rounded_to'] %></td>
    <td><%= metric['currency_code'] %></td>
</tr>

app/views/metrics/index.html.erb
<h1>Hoopla Metrics</h1>
<table>
    <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Format</th>
        <th>Currency</th>
    </tr>
    <%= render partial: 'metrics', collection: @metrics, as: :metric %>
</table>